# Generated by Django 5.0.7 on 2024-07-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='speciality',
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
