# Generated by Django 5.0.7 on 2024-07-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_speciality_speciality_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciality',
            old_name='speciality',
            new_name='course',
        ),
    ]
