# Generated by Django 5.0.7 on 2024-07-14 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.ManyToManyField(blank=True, to='blog.comments'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 14, 9, 18, 9, 385501)),
        ),
    ]
